openapi: 3.0.0
info:
  title: Zendire E-commerce API
  version: 1.0.0
  description: Zendire E-commerce Application API Documentation
  contact:
    name: ''
    url: ''
    email: ''
servers:
  - url: http://localhost:5000
components:
  schemas:
    Product:
      type: object
      required:
        - name
        - description
        - price
        - sku
        - numberOfProductsAvailable
      properties:
        name:
          type: string
          description: The name of the product
        description:
          type: string
          description: The description of the product
        price:
          type: number
          description: The price of the product
        sku:
          type: string
          description: The SKU of the product
        numberOfProductsAvailable:
          type: number
          description: The number of product available
        images:
          type: array
          items:
            type: string
            format: binary
          description: The list of product images
      example:
        name: Sample Product
        description: This is a sample product
        price: 99.99
        sku: SAMPLE-SKU-001
        numberOfProductsAvailable: 100
        images: []
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  - name: product
    description: The product managing API
paths:
  /api/product:
    get:
      summary: Returns the list of all the product
      tags: [product]
      responses:
        200:
          description: The list of the product
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /api/product/new:
    post:
      summary: Create a new product
      tags: [product]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                price:
                  type: number
                sku:
                  type: string
                numberOfProductsAvailable:
                  type: number
                images:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        201:
          description: The product was successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        400:
          description: Some fields are missing
        401:
          description: Unauthorized
  /api/product/update/{sku}:
    put:
      summary: Update a product
      tags: [product]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: sku
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                price:
                  type: number
                numberOfProductsAvailable:
                  type: number
                images:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        200:
          description: The product was successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        400:
          description: The SKU is missing
        401:
          description: Unauthorized
        404:
          description: The product was not found
  /api/product/delete/{sku}:
    delete:
      summary: Delete a product
      tags: [product]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: sku
          schema:
            type: string
          required: true
      responses:
        200:
          description: The product was successfully deleted
        400:
          description: The SKU is missing
        401:
          description: Unauthorized
        404:
          description: The product was not found
  /api/product/{sku}:
    get:
      summary: Get a product by SKU
      tags: [product]
      parameters:
        - in: path
          name: sku
          schema:
            type: string
          required: true
      responses:
        200:
          description: The product description by SKU
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        400:
          description: The SKU is missing
        404:
          description: The product was not found
